apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-ml-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jeizz/Taller_CI_CD.git
    targetRevision: HEAD
    path: Niveles/4/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
