apiVersion: v1
kind: Service
metadata:
  name: api-inferencia-service
spec:
  type: NodePort
  selector:
    app: api-inferencia
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
